---
version: '3.4'
volumes:
  fedora4:
  fedora5:
  db:
  solr_repo:
  solr_index:
services:
  fedora4:
    image: nulib/fcrepo4:4.7.5
    volumes:
    - fedora4:/data
    ports:
    - 8988:8080
  fedora5:
    image: nulib/fcrepo4:5.0.0
    volumes:
    - fedora5:/data
    ports:
    - 8998:8080
  db:
    image: healthcheck/postgres:alpine
    volumes:
    - db:/data
    environment:
    - PGDATA=/data
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=d0ck3r
    ports:
    - 5434:5432
  solr_repo:
    image: solr:7.2-alpine
    ports:
    - 8984:8983
    volumes:
    - solr_repo:/opt/solr/server/solr/mycores
    - "../../solr:/solr_config"
    entrypoint:
    - docker-entrypoint.sh
    - solr-precreate
    - blacklight-core-test
    - "/solr_config/config"
    healthcheck:
      test:
      - CMD
      - wget
      - "-O"
      - "/dev/null"
      - http://localhost:8983/solr/
      interval: 30s
      timeout: 5s
      retries: 3
