development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8986/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8988/rest
  base_path: /test
